### ISSUE TITLE
Doesn't seem to compile with GHC 8.2.2

### ISSUE THREAD

**Issue by jchia** [vacationlabs/record-splicer#2]
Under lts-10.0, I'm getting this error when trying to build the package:
```
    Building library for record-splicer-0.1.0.0..
    [1 of 1] Compiling RecordSplicer    ( src/RecordSplicer.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/RecordSplicer.o )
    
    /home/jchia/hs/doc/.stack-work/downloaded/0IsY9NPFwi6J/src/RecordSplicer.hs:107:73: error:
        • Couldn't match type ‘Type’ with ‘DerivClause’
          Expected type: [DerivClause]
            Actual type: [Type]
        • In the sixth argument of ‘DataD’, namely
            ‘(map ConT deriveClasses)’
          In the expression:
            DataD
              ctx
              tName
              targetParamVars
              kind
              [RecC tName targetFields]
              (map ConT deriveClasses)
          In the expression:
            [DataD
               ctx
               tName
               targetParamVars
               kind
               [RecC tName targetFields]
               (map ConT deriveClasses),
             DataD
               ctx
               dName
               deltaParamVars
               kind
               [RecC dName deltaFields]
               (map ConT deriveClasses),
             SigD
               fsName
               (AppT
                  (AppT ArrowT (createTySigD source $ kindedTyVarsToTypes tyVars))
                  (createTySigD tName $ kindedTyVarsToTypes targetParamVars)),
             FunD
               fsName
               [Clause
                  [...]
                  (NormalB
                     $ RecConE tName
                         $ getRecConE targetFields id (targetToSourceName args) tVariable)
                  []],
             ....]
        |
    107 |         DataD ctx tName targetParamVars kind [RecC tName targetFields] (map ConT deriveClasses)
        |                                                                         ^^^^^^^^^^^^^^^^^^^^^^
...
```

**Comment by jchia** [comment]
The breakage is due to a change to the definition of `DataD` in the newer ghc. The type of the last argument has changed to support specifying deriving strategies. CPP extension to enable supporting multiple GHC versions? Would the th-abstraction package be helpful for this problem?

**Comment by pranaysashank** [comment]
We were aware of this issue, the `latest` branch in the repo supports GHC 8.2.1. Using CPP extension seems to be the easier way to fix this.
